# export SPRING_PROFILES_ACTIVE=dev2
#####################################################################
# MariaDB for Subscriber management
spring.datasource.url=jdbc:mariadb://10.89.89.61:3306/kamailio
spring.datasource.username=skychatuc
spring.datasource.password=skychatucrw
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# ------------------------------------------------------------------
# Turn off the DDL generation
# We have to set the value carefully or use one of the other mechanisms to initialize the database.
# DDL: Data Definition Language
# none, validate, update, create-drop: default create-drop
# * create ? Hibernate first drops existing tables, then creates new tables
# * update ? the object model created based on the mappings (annotations or XML) is compared with the existing schema, and then Hibernate updates the schema according to the diff. It never deletes the existing tables or columns even if they are no more required by the application
# * create-drop ? similar to create, with the addition that Hibernate will drop the database after all operations are completed. Typically used for unit testing
# * validate ? Hibernate only validates whether the tables and columns exist, otherwise it throws an exception
# * none ? this value effectively turns off the DDL generation
spring.jpa.hibernate.ddl-auto=none
# ------------------------------------------------------------------
#SSL Key Info
security.require-ssl=false
#server.ssl.key-store-password=r83Ng0oQYUwaSnm
#server.ssl.key-store=/home/june/voip_proxy/skychat.p12
#server.ssl.key-store-type=PKCS12

# Firebase Cloud Messaging
app.firebase-configuration-file=/home/june/voip_proxy/egovoip-firebase-adminsdk-t09m9-7ebcf375e4.json